# Generated by Django 4.1.5 on 2023-01-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilidades', '0001_initial'),
        ('Core', '0002_alter_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Utilidades',
            field=models.ManyToManyField(to='Utilidades.utilidade'),
        ),
    ]
