# Generated by Django 4.1.5 on 2023-01-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enderecos', '0001_initial'),
        ('Core', '0004_pontoturistico_avaliacoes_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enderecos.endereco'),
            preserve_default=False,
        ),
    ]
