# Generated by Django 4.1.5 on 2023-01-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilidade',
            name='horario_func',
        ),
        migrations.RemoveField(
            model_name='utilidade',
            name='idade_minima',
        ),
    ]
